app_operatorsgroups:
    resource: |
        alias: salaryj.operatorsgroups
        except: ['show']
        path: /operators-groups
        templates: "salary-j/pages/OperatorsGroups"
    type: sylius.resource
    
app_operators:
    resource: |
        alias: salaryj.operators
        except: ['show']
        path: /operators
        templates: "salary-j/pages/Operators"
    type: sylius.resource

app_models:
    resource: |
        alias: salaryj.models
        except: ['show']
        path: /models
        templates: "salary-j/pages/Models"
    type: sylius.resource    
    

app_json_models:
    path: /json/models
    controller: App\Controller\SalaryJ\ModelsExtController::jsonListModels

app_model_browse_operations_get:
    path: /model-operations/browse-get
    controller: App\Controller\SalaryJ\ModelsExtController::browseOperationsGet

app_model_browse_operations:
    path: /model-operations/{modelId}/browse
    controller: App\Controller\SalaryJ\ModelsExtController::browseOperations
    
app_model_add_operations:
    path: /model-operations/{modelId}/add
    controller: App\Controller\SalaryJ\ModelsExtController::addOperations
    
app_model_add_operations_new:
    path: /model-operations/{modelId}/add_new
    controller: App\Controller\SalaryJ\ModelsExtController::addOperationsNew
    
app_operators_work_browse_operations:
    path: /operators-work/{operatorId}/browse
    controller: App\Controller\SalaryJ\OperatorsWorkController::browseOperations
    
app_operators_work_add_operations:
    path: /operators-work/{operatorId}/add
    controller: App\Controller\SalaryJ\OperatorsWorkController::addOperations
