app_operatorsgroups:
    resource: |
        alias: salaryj.operatorsgroups
        except: ['show']
        path: /operators-groups
        templates: "salary-j/pages/OperatorsGroups"
    type: sylius.resource
    
app_operators:
    resource: |
        alias: salaryj.operators
        except: ['show']
        path: /operators
        templates: "salary-j/pages/Operators"
    type: sylius.resource

app_models:
    resource: |
        alias: salaryj.models
        except: ['show']
        path: /models
        templates: "salary-j/pages/Models"
    type: sylius.resource    

app_operations:
    resource: |
        alias: salaryj.operations
        except: ['show']
        path: /operations
        templates: "salary-j/pages/Operations"
    type: sylius.resource
    
app_operators_work_browse:
    path: /operators-work/{operatorId}
    controller: App\Controller\SalaryJ\OperatorsWorkController::browseOperations
