app_operatorsgroups:
    resource: |
        alias: salaryj.operatorsgroups
        except: ['show']
        path: /operators-groups
        templates: "salary-j/pages/OperatorsGroups"
#    defaults:
#      _sylius:
#          form: salary_j.form.operatorsgroups
    type: sylius.resource
    
app_operators:
    resource: |
        alias: salaryj.operators
        except: ['show']
        path: /operators
        templates: "salary-j/pages/Operators"
    type: sylius.resource

app_models:
    resource: |
        alias: salaryj.models
        except: ['show']
        path: /models
        templates: "salary-j/pages/Models"
    type: sylius.resource    

app_operations:
    resource: |
        alias: salaryj.operations
        except: ['show']
        path: /operations
        templates: "salary-j/pages/Operations"
    type: sylius.resource
    
app_operators_work:
    resource: |
        alias: salaryj.operatorswork
        except: ['show']
        path: /operators-work
        templates: "salary-j/pages/OperatorsWork"
    type: sylius.resource

#app_operators:
#    path: /operators
#    controller: App\Controller\SalaryJ\OperatorsController::index