app_operatorsgroups_index:
    path: /operators-groups/
    methods: [GET]
    defaults:
        _controller: salaryj.controller.operatorsgroups::indexAction
        _sylius:
            paginate: 30
            sorting:
                score: desc
            filterable: true
            criteria:
                application: 3  # Show Items Only For This Application
            template: "pages/OperatorsGroups/index.html.twig"

app_operatorsgroups:
    resource: |
        alias: salaryj.operatorsgroups
        except: ['show']
        path: /operators-groups
        templates: "pages/OperatorsGroups"
    type: sylius.resource
    options:
        expose: true

app_operators_index:
    path: /operators/{groupId}/
    methods: [GET]
    defaults:
        _controller: salaryj.controller.operators::indexAction
        _sylius:
            paginate: 30
            sorting:
                score: desc
            filterable: true
            criteria:
                group: $groupId
                application: 3  # Show Items Only For This Application
            template: "pages/Operators/index.html.twig"
    options:
        expose: true
              
app_operators:
    resource: |
        alias: salaryj.operators
        except: ['show']
        path: /operators/{groupId}
        templates: "pages/Operators"
    type: sylius.resource
    options:
        expose: true

app_models_index:
    path: /models/
    methods: [GET]
    defaults:
        _controller: salaryj.controller.models::indexAction
        _sylius:
            paginate: 30
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                application: 3  # Show Items Only For This Application
            template: "pages/Models/index.html.twig"
    options:
        expose: true
    
app_models:
    resource: |
        alias: salaryj.models
        except: ['show']
        path: /models
        templates: "pages/Models"
    type: sylius.resource

app_operations_index:
    path: /operations/{modelId}/
    methods: [GET,POST]
    defaults:
        _controller: salaryj.controller.operations::indexAction
        _sylius:
            paginate: 30
            sorting:
                operationId: asc
            filterable: true
            criteria:
                model: $modelId
                application: 3  # Show Items Only For This Application
            template: "pages/Operations/index.html.twig"
    options:
        expose: true

app_operations:
    resource: |
        alias: salaryj.operations
        except: ['show']
        path: /operations
        templates: "pages/Operations"
    type: sylius.resource
