vs_user_proffile:
    resource: "@VSUsersBundle/Resources/config/routing/profile.yml"
    prefix:   /

app_login:
    path: /login
    controller: App\Controller\SalaryJ\AuthController::login

app_logout:
    path: /logout
    controller: App\Controller\SalaryJ\AuthController::logout

