sylius_resource:
    resources:
        salaryj.operatorsgroups: 
            driver: doctrine/orm
            classes:
                model:      App\Entity\OperatorsGroup
                interface:  Sylius\Component\Resource\Model\ResourceInterface
                controller: App\Controller\SalaryJ\OperatorsGroupsController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                form:       App\Form\OperatorsGroupForm
        salaryj.operators:
            driver: doctrine/orm
            classes:
                model:      App\Entity\Operator
                interface:  Sylius\Component\Resource\Model\ResourceInterface
                controller: App\Controller\SalaryJ\OperatorsController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                form:       App\Form\OperatorForm
 
        salaryj.models:
            driver: doctrine/orm
            classes:
                model:      App\Entity\Model
                interface:  Sylius\Component\Resource\Model\ResourceInterface
                controller: App\Controller\SalaryJ\ModelsController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                form:       App\Form\ModelForm
  
        salaryj.operations:
            driver: doctrine/orm
            classes:
                model:      App\Entity\Operation
                interface:  Sylius\Component\Resource\Model\ResourceInterface
                controller: App\Controller\SalaryJ\OperationsController
                repository: App\Repository\OperationsRepository
                form:       App\Form\OperationForm
                
        salaryj.settings:
            driver: doctrine/orm
            classes:
                model:      App\Entity\Settings
                repository: App\Repository\SettingsRepository
                factory: Sylius\Component\Resource\Factory\Factory
