sylius_resource:
    #translation:
        #default_locale: '%locale%'
        #locale_provider: sylius.translation.locale_provider.contextual
        #available_locales_provider: sylius.translation.locales_provider
    resources:
        salaryj.operatorsgroups:
            driver: doctrine/orm
            classes:
                model:      App\Entity\OperatorsGroup
                interface:  Sylius\Component\Resource\Model\ResourceInterface
                controller: App\Controller\JunonaTestApplication\OperatorsGroupsController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                form:       App\Form\OperatorsGroupForm
                factory: Sylius\Component\Resource\Factory\Factory
                
        salaryj.operators:
            driver: doctrine/orm
            classes:
                model:      App\Entity\Operator
                interface:  Sylius\Component\Resource\Model\ResourceInterface
                controller: App\Controller\JunonaTestApplication\OperatorsController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                form:       App\Form\OperatorForm
                factory: Sylius\Component\Resource\Factory\Factory
 
        salaryj.models:
            driver: doctrine/orm
            classes:
                model:      App\Entity\Model
                interface:  Sylius\Component\Resource\Model\ResourceInterface
                controller: App\Controller\JunonaTestApplication\ModelsController
                repository: App\Repository\ModelsRepository
                form:       App\Form\ModelForm
                factory: Sylius\Component\Resource\Factory\Factory
  
        salaryj.operations:
            driver: doctrine/orm
            classes:
                model:      App\Entity\Operation
                interface:  Sylius\Component\Resource\Model\ResourceInterface
                controller: App\Controller\JunonaTestApplication\OperationsController
                repository: App\Repository\OperationsRepository
                form:       App\Form\OperationForm
                factory: Sylius\Component\Resource\Factory\Factory
                
        salaryj.settings:
            driver: doctrine/orm
            classes:
                model:      App\Entity\Settings
                repository: App\Repository\SettingsRepository
                factory: Sylius\Component\Resource\Factory\Factory

        salaryj.operators_work:
            driver: doctrine/orm
            classes:
                model:      App\Entity\OperatorsWork
                repository: App\Repository\OperatorsWorkRepository
                factory: Sylius\Component\Resource\Factory\Factory
        

        

