twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    
    globals:
        app_environment: '%env(APP_ENV)%'
        applicationCompany: '%applicationCompany%'
        applicationTitle: '%applicationTitle%'
        hasTopSearch: '%hasTopSearch%'
        locale: '%locale%'
        formCreateAccount: '%vs_users.form_create_account%'
        installedBundles: '%kernel.bundles%'
        
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    