framework:
    assets:
        packages:
            default:
                json_manifest_path: '%kernel.project_dir%/public/salary-j/build/default/manifest.json'
            test-theme:
                json_manifest_path: '%kernel.project_dir%/public/salary-j/build/test-theme/manifest.json'

webpack_encore:
    output_path: '%kernel.project_dir%/public/salary-j/build/default'
    builds:
        defaultConfig: '%kernel.project_dir%/public/salary-j/build/default'
        testThemeConfig: '%kernel.project_dir%/public/salary-j/build/test-theme'

