app_home:
    path: /
    controller: App\Controller\SalaryJ\DefaultController::index

admin_panel:
    path: /admin
    controller: App\Controller\Application\DefaultController::openAdminPanel

app_set_lang:
    path: /set_lang/{lang}
    controller: App\Controller\SalaryJ\DefaultController::setLanguage

app_set_locale:
    path: /set_locale/{locale}
    controller: App\Controller\SalaryJ\DefaultController::setLocale
