app_home:
    path: /
    controller: App\Controller\SalaryJ\DefaultController::index

admin_panel:
    path: /admin
    controller: App\Controller\Application\DefaultController::openAdminPanel

app_set_lang:
    path: /set_lang/{lang}
    controller: App\Controller\Aplication\DefaultController::setLanguage
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"
