parameters:
    lang: 'bg'
    locale: 'bg_BG'
    languages:
        en: English
        bg: Български
    
    vankosoft_host: '%env(HOST)%'
    
    siteTitle: 'SalaryJ'
    vs_application.menu.config_file: "%kernel.project_dir%/config/applications/salary-j/packages/vs_application.yaml"
    
    vs_users.login_route: 'app_login'
    vs_users.login_by: 'username'
    vs_users.default_redirect: 'app_operators'
    vs_users.api_token.lifetime: 3600
    vs_user.profile_pictures_dir: '%kernel.project_dir%/var/uploads/profile_pictures'
    
    yaml.parser.class: Symfony\Component\Yaml\Parser
    menu.config_file: "%kernel.project_dir%/../config/sites/salary-j/packages/vs_application.yaml"

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../../../src/*'
        exclude: '../../../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
        autowire: true
        
    App\Controller\:
        resource: '../../../src/Controller'
        tags: ['controller.service_arguments']
        autowire: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
