imports:
    - { resource: services/salary_j.yaml }
    - { resource: services/doctrine_extensions.yaml }
    - { resource: services/forms.yaml }

parameters:
    lang: 'bg'
    locale: 'bg_BG'
    languages:
        en: English
        bg: Български
    
    vankosoft_host: '%env(HOST)%'
    applicationTitle: 'SalaryJ'
    
    vs_application.version: !php/const App\SalaryJKernel::VERSION
    vs_application.menu.config_file: "%kernel.project_dir%/config/applications/salary-j/packages/vs_application.yaml"
    vs_application.public_dir: "%kernel.project_dir%/public/salary-j"
    
    vs_users.login_route: 'app_login'
    vs_users.login_by: 'username'
    vs_users.default_redirect: 'app_operators'
    vs_users.cookie_lifetime: 3600
    vs_users.api_token.lifetime: 3600
    vs_user.profile_pictures_dir: '%kernel.project_dir%/var/uploads/profile_pictures'
    
    yaml.parser.class: Symfony\Component\Yaml\Parser

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../../../src/*'
        exclude: '../../../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
        autowire: false
        
    App\Controller\:
        resource: '../../../src/Controller'
        tags: ['controller.service_arguments']
        autowire: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
