services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\JunonaTestApplication\:
        resource: '../../../../src/Controller/JunonaTestApplication'
        tags: ['controller.service_arguments']
        autowire: true
    
    App\Controller\JunonaTestApplication\AuthController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
    
    App\Controller\JunonaTestApplication\DefaultController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'

    App\Controller\JunonaTestApplication\UsersController:
        arguments:
            - '@doctrine'
            - '@vs_application.context.application'
            - '@vs_application.repository.application'
            - '@vs_users.manager.user'
            - '@vs_users.repository.users'
            - '@vs_users.factory.users'
            - '@vs_users.factory.user_info'
            - '@vs_users.repository.user_roles'
        tags: ['controller.service_arguments']
    
    App\Controller\JunonaTestApplication\OperatorsGroupsExtController:
        arguments:
            - '@doctrine'
            - "@vs_application.context.application"
            - '@salaryj.repository.operatorsgroups'
            - '@vs_application.slug_generator'
        tags: ['controller.service_arguments']
        
    App\Controller\JunonaTestApplication\OperatorsExtController:
        arguments:
            - '@doctrine'
            - "@vs_application.context.application"
            - '@salaryj.repository.operators'
        tags: ['controller.service_arguments']
        
    App\Controller\JunonaTestApplication\ModelsExtController:
        arguments:
            - '@doctrine'
            - '@twig'
            - '@translator'
            - "@vs_application.context.application"
            - "@salaryj.repository.models"
            - "@salaryj.repository.operations"
            - '@salaryj.repository.operators'
            - "@salaryj.repository.settings"
            - '@salaryj.repository.operators_work'
        tags: ['controller.service_arguments']
        
    App\Controller\JunonaTestApplication\SettingsController:
        arguments:
            - '@doctrine'
            - '@vs_application.context.application'
            - '@salaryj.repository.settings'
            - '@salaryj.factory.settings'
        tags: ['controller.service_arguments']
        
    App\Controller\JunonaTestApplication\OperationsExtController:
        arguments:
            - '@doctrine'
            - '@vs_application.context.application'
            - '@salaryj.repository.models'
            - "@salaryj.repository.settings"
            - '@salaryj.repository.operations'
            - '@salaryj.factory.operations'
        tags: ['controller.service_arguments']
        
    App\Controller\JunonaTestApplication\OperatorsWorkController:
        arguments:
            - '@doctrine'
            - '@twig'
            - '@translator'
            - '@knp_paginator'
            - '@vs_application.context.application'
            - '@salaryj.repository.operators'
            - '@salaryj.repository.operators_work'
            - '@salaryj.repository.models'
            - '@salaryj.repository.operations'
            - '@salaryj.repository.operatorsgroups'
            - '@salaryj.repository.settings'
        tags: ['controller.service_arguments']

    App\Controller\JunonaTestApplication\PrintController:
        arguments:
            - '@translator'
            - '@vs_application.context.application'
            - '@salaryj.repository.operators'
            - '@salaryj.repository.operators_work'
            - '@salaryj.repository.operatorsgroups'
            - '@salaryj.repository.models'
        tags: ['controller.service_arguments']
    
    