services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\:
        resource: '../../../../src/Controller'
        tags: ['controller.service_arguments']
        
    App\Controller\SalaryJ\ModelsExtController:
        arguments:
            - "@vs_application.context.application"
            - "@salaryj.repository.models"
            - "@salaryj.repository.operations"
            - "@salaryj.repository.settings"
        tags: ['controller.service_arguments']
        
    App\Controller\SalaryJ\SettingsController:
        arguments:
            - '@vs_application.context.application'
            - '@salaryj.repository.settings'
            - '@salaryj.factory.settings'
        tags: ['controller.service_arguments']
        
    App\Controller\SalaryJ\OperationsExtController:
        arguments:
            - '@vs_application.context.application'
            - '@salaryj.repository.models'
            - '@salaryj.repository.operations'
            - '@salaryj.factory.operations'
        tags: ['controller.service_arguments']
