parameters:
    vs_users.registration_form_required_fields: []

services:
    _defaults:
        autowire: true
        autoconfigure: true

    salaryj.resources.operatorsgroups.form:
        class: App\Form\OperatorsGroupForm
        arguments:
            - "%salaryj.model.operatorsgroups.class%"
            - '@vs_application.repository.locale'
            - '@request_stack'
            - "@salaryj.repository.operatorsgroups"
        tags:
            - { name: form.type }

    salaryj.resources.operators.form:
        class: App\Form\OperatorForm
        arguments:
            - "%salaryj.model.operators.class%"
            - '@vs_application.repository.locale'
            - '@request_stack'
        tags:
            - { name: form.type }
    
    salaryj.resources.models.form:
        class: App\Form\ModelForm
        arguments:
            - "%salaryj.model.models.class%"
            - '@vs_application.repository.locale'
            - '@request_stack'
        tags:
            - { name: form.type }
            
    salaryj.resources.operations.form:
        class: App\Form\OperationForm
        arguments:
            - "%salaryj.model.operations.class%"
            - '@vs_application.repository.locale'
            - '@request_stack'
        tags:
            - { name: form.type }
    
    salaryj.resources.users.form:
        class: App\Form\UserForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_users.model.users.class%'
            - '@vs_application.repository.locale'
            - "@request_stack"
            - '%vs_application.model.application.class%'
            - '@security.helper'
            - '%vs_users.registration_form_required_fields%'
            - '@salaryj.component.orm'
            
    App\Form\Type\OperatorType:
        tags:
            - { name: form.type }
        arguments:
            - '@vs_application.context.application'
            
    App\Form\OperatorFilterForm:
        tags:
            - { name: form.type }
        arguments:
            - '@vs_application.context.application'

    