services:
    _defaults:
        autowire: true
        autoconfigure: true

    salaryj.resources.operatorsgroups.form:
        class: App\Form\OperatorsGroupForm
        arguments:
            - "%salaryj.model.operatorsgroups.class%"
            - "@salaryj.repository.operatorsgroups"
        tags:
            - { name: form.type }

