parameters:
    salary_j.operators_groups.taxonomy_code: operators-groups

services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    salaryj.component.orm:
        class: App\Component\Orm
        arguments:
            - '@translator'

